#! /bin/sh

echo "¶ Running ruff..." && ruff check --fix kdl && echo "¶ Running black..." && black kdl && echo "¶ Running mypy..." && mypy kdl && echo "¶ Running pylint..." && pylint kdl && echo "✔ All lints passed!"